import { Inter } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });
import Card from "@/components/Card";
import Link from "next/link";
import InputLabel from "@/components/inputs/InputLabel";
import Description from "@/components/DecriptionComponent";
import Button from "@/components/Button";
import DashboardTable from "@/components/DashBoardTable";
export default function Home() {
  const goToNewModl = () => {

  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900">
        <div className="lg:w-full flex flex-col md:flex-row">
          <div className="lg:w-1/4 m-2">
            <Card className="flex flex-col items-center">
              <InputLabel>Upload a new background</InputLabel>
              <Link href={`/background/upload`}>
                <Button>Upload Backgrounds</Button>
              </Link>
            </Card>
          </div>
          <div className="lg:w-1/4 m-2">
            <Card className="flex flex-col items-center">
              <InputLabel>Upload a new model</InputLabel>
              <Link href={`/model/upload`}>
                <Button>Upload Model</Button>
              </Link>
            </Card>
          </div>
          <div className="lg:w-1/4 m-2">
            <Card className="flex flex-col items-center">
              <InputLabel>Create a new netwrok</InputLabel>
              <Link href={`/network/create`}>
                <Button>New Network</Button>
              </Link>
            </Card>
          </div>
          <div className="lg:w-1/4 m-2">
            <Card className="flex flex-col items-center">
              <InputLabel>Create a new dataset</InputLabel>
              <Link href={`/dataset/create`}>
                <Button>New Dataset</Button>
              </Link>
            </Card>
          </div>
        </div>
        <Description
          title="Tasks"
          description="An overview of the tasks"
          imageUrl="https://img.freepik.com/vektoren-premium/papier-klemmbrett-mit-brief-buerobedarf-kritzeln-lineare-cartoon-faerbung_253359-5740.jpg?w=1060"
        />
        <DashboardTable/>
      </main>
    </>
  );
}
