import { Inter } from "@next/font/google";
import Head from "next/head";

import ButtonCard from "@/components/dashboard/ButtonCard";
import DashboardTable from "@/components/dashboard/DashBoardTable";

import { DashboardButtons } from "shared-types";

const inter = Inter({ subsets: ["latin"] });

const Dashboard: React.FC = () => (
  <div className="container mx-auto">
    <Head>
      <title>Dashboard | CV-Bench</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="space-y-4">
      <div className="border-b border-slate-600 pb-4">
        <div className="grid grid-cols-4 gap-4">
          {DashboardButtons.map(({ title, description, href }) => (
            <ButtonCard title={title} description={description} href={href} />
          ))}
        </div>
      </div>

      <DashboardTable />
    </main>
  </div>
);

export default Dashboard;
